qemu_guest_agent: adjust check method for isa-serial situation
autotest/tp-qemu pull request #3781
Opened 2023-07-20 01:18 UTC by 6-dehan

since there is a minor change for starting qemu-ga.exe, it will display debug info about version of mingw-qemu-ga so that auto program couldn't catch the expected condition to determine cmd run finished. so remove invaluable parameter '-v' after confirm with dev.

ID: 2199116
Signed-off-by: demeng <demeng@redhat.com>

2023-07-21 03:28 UTC, 6-dehan commented
@vivianQizhu could you please help to review?  @MiriamDeng @fbq815  @BohdanMar does it affect your scenario? if so, please help to review it. 
 (01/10) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (01/10) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (188.77 s)
 (02/10) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (02/10) repeat1.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (103.92 s)
 (03/10) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (03/10) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (58.97 s)
 (04/10) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (04/10) repeat2.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (102.53 s)
 (05/10) repeat3.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (05/10) repeat3.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (58.93 s)
 (06/10) repeat3.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (06/10) repeat3.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (103.02 s)
 (07/10) repeat4.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (07/10) repeat4.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (59.20 s)
 (08/10) repeat4.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (08/10) repeat4.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (104.74 s)
 (09/10) repeat5.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (09/10) repeat5.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (58.20 s)
 (10/10) repeat5.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: STARTED
 (10/10) repeat5.Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.Win2022.x86_64.io-github-autotest-qemu.qemu_guest_agent.isa_serial.gagent_check_log.q35: PASS (103.54 s)
RESULTS    : PASS 10 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/kar/workspace/job-results/job-2023-07-20T22.57-0810c37/results.html
JOB TIME   : 948.92 s

2023-07-26 11:39 UTC, BohdanMar commented
This case isn't supported on aarch64, no affection.

2023-07-31 08:30 UTC, vivianQizhu commented on qemu/tests/qemu_guest_agent.py
> +            if not log_str:
This would make the checkpoint meaningless, I would suggest to check at least the command return value if we don't check the detail content.

2023-07-31 08:58 UTC, vivianQizhu requested changes
As comment in line, please check.

2023-08-24 09:37 UTC, closed without merging

2023-08-24 09:37 UTC, 6-dehan commented
something goes wrong.