boot_from_virtiofs: Add aarch64 console "ttyAMA0"
autotest/tp-qemu pull request #3782
Opened 2023-07-24 05:21 UTC by SiboWang1997

Add console for aarch64.

ID: 2215182
Signed-off-by: Sibo Wang siwang@redhat.com

2023-07-24 06:08 UTC, SiboWang1997 commented
JOB ID     : a3ab48cc1bbfddeee54021af5e9916ab27a72ad3
JOB LOG    : /root/avocado/job-results/job-2023-07-23T23.10-a3ab48c/job.log
 (1/1) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.boot_from_virtiofs.arm64-pci: STARTED
 (1/1) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.boot_from_virtiofs.arm64-pci: PASS (166.19 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-07-23T23.10-a3ab48c/results.html
JOB TIME   : 167.34 s

2023-07-24 06:23 UTC, SiboWang1997 commented
Hello @YongxueHong @zhenyzha @xiagao , could you help me review this patch when you are free? Thanks a lot.

2023-07-24 06:47 UTC, YongxueHong commented on qemu/tests/cfg/boot_from_virtiofs.cfg
> +        kernel_params = "root=virtiofs:${fs_target} console=ttyAMA0"
```suggestion
    kernel_params = "root=virtiofs:${fs_target} console=ttyS0"
    aarch64:
        kernel_params = "root=virtiofs:${fs_target} console=ttyAMA0"
```

2023-07-24 09:13 UTC, YongxueHong submitted a review, later dismissed

2023-07-24 11:25 UTC, zhenyzha commented
git am 3782.patch
Applying: boot_from_virtiofs: Add aarch64 console "ttyAMA0"

```
 (1/2) Host_RHEL.m9.u3.qcow2.virtio_blk.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.boot_from_virtiofs.arm64-pci: PASS (167.53 s)
 (2/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.boot_from_virtiofs.arm64-pci: PASS (163.51 s)
```

LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

2023-07-24 11:25 UTC, zhenyzha approved these changes

2023-07-25 07:05 UTC, PaulYuuu requested changes

2023-07-25 07:05 UTC, PaulYuuu commented on qemu/tests/cfg/boot_from_virtiofs.cfg
> +        kernel_params = "root=virtiofs:${fs_target} console=ttyAMA0"
We should consider all architectures, in my opinion:
```suggestion
    x86_64, i386:
        console_dev = "ttyS0,115200"
    ppc64le, ppc64:
        console_dev = "hvc0,38400"
    aarch64:
        console_dev = "ttyAMA0,38400"
    s390x:
        console_dev = "ttysclp0,38400"
    kernel_params = "root=virtiofs:${fs_target} console=${console_dev}"
        
```

2023-07-26 03:05 UTC, SiboWang1997 commented
Hi @fbq815 @MiriamDeng ,could you please help review this patch when you are free? Thanks a lot.

2023-08-01 02:20 UTC, MiriamDeng commented
> Add console for aarch64.
> 
> ID: 2215182 Signed-off-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

Here, we should remove aarch64 here.

2023-08-10 08:25 UTC, MiriamDeng commented
ACK

2023-08-14 01:25 UTC, PaulYuuu approved these changes

2023-08-14 03:19 UTC, YongxueHong commented
Hi @SiboWang1997 
For the CI checking failure, please rebase(update) your development branch to the latest.
Thanks.

2023-08-14 05:33 UTC, SiboWang1997 commented
> Hi @SiboWang1997 For the CI checking failure, please rebase(update) your development branch to the latest. Thanks.

The CI checking failure is caused by #3786 , should I update the branch when #3786 merged?

2023-08-17 01:42 UTC, PaulYuuu approved these changes

2023-08-17 01:43 UTC, PaulYuuu commented
@SiboWang1997 Now you can rebase your branch to fix the CI issue.

2023-08-17 01:45 UTC, YongxueHong approved these changes

2023-08-17 02:20 UTC, PaulYuuu commented
Thanks all.

2023-08-17 02:20 UTC, merged