Updated virtio-fs test cases on s390x
autotest/tp-qemu pull request #3802
Opened 2023-08-24 09:26 UTC by fbq815

Virtio_fs: since we could set up memory-backend without numa/hugepage, remove workaround for virtio_fs ralated test cases on s390x

ID: 2213759

Signed-off-by: Boqiao Fu <bfu@redhat.com>

2023-08-28 09:50 UTC, fbq815 commented
Test result:
SE:
JOB ID     : ebbe3d308416b22aa6daa2a32f4ffbc63f7dc4c6
JOB LOG    : /root/avocado/job-results/job-2023-08-28T05.22-ebbe3d3/job.log
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: PASS (32.41 s)
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_readonly.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_readonly.s390-virtio: PASS (28.09 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-08-28T05.22-ebbe3d3/results.html
JOB TIME   : 62.47 s

Normal:
JOB ID     : b27ff14345055f6045233d42509b746d55b0959a
JOB LOG    : /root/avocado/job-results/job-2023-08-28T05.46-b27ff14/job.log
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_readonly.s390-virtio: STARTED
 (1/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_readonly.s390-virtio: PASS (26.88 s)
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: STARTED
 (2/2) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: PASS (30.59 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-08-28T05.46-b27ff14/results.html
JOB TIME   : 59.54 s


@xiagao @MiriamDeng @zhenyzha could you please help me review this patch on your platform?

2023-08-29 06:05 UTC, xiagao commented
(1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: STARTED
 (1/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: PASS (81.42 s)
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.q35: STARTED
 (2/2) Host_RHEL.m9.u3.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.q35: PASS (108.70 s)

It looks good for x86.

2023-08-30 05:54 UTC, SiboWang1997 commented
JOB ID     : 568cd3fcb96ead238829e38fe5b656b5b8f6dd6b
JOB LOG    : /root/avocado/job-results/job-2023-08-30T01.40-568cd3f/job.log
 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: STARTED
 (1/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: PASS (45.72 s)
 (2/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.arm64-pci: STARTED
 (2/2) Host_RHEL.m9.u3.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.arm64-pci: PASS (68.41 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-08-30T01.40-568cd3f/results.html
JOB TIME   : 115.70 s

LGTM,
Acked-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

2023-08-30 06:41 UTC, MiriamDeng commented
For rhel 8.9.0 and rhel 9.0.0
 (1/2) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly: STARTED
 (1/2) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.9.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly: PASS (97.89 s)
 (2/2) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly: STARTED
 (2/2) Host_RHEL.m8.u9.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.ppc64le.io-github-autotest-qemu.virtio_fs_readonly: PASS (115.67 s)

2023-08-30 08:45 UTC, fbq815 commented
@PaulYuuu please help me review this patch

2023-08-30 08:46 UTC, fbq815 commented
@SiboWang1997 @xiagao @MiriamDeng if it's working on your platform, please give me an approve, thanks

2023-08-31 02:03 UTC, MiriamDeng commented
ACK

2023-08-31 02:47 UTC, zhenyzha commented
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>

git am 3802.patch
Applying: Updated virtio-fs test cases on s390x

```
 (1/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: STARTED
 (1/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: PASS (100.75 s)
 (2/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.arm64-pci: STARTED
 (2/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.arm64-pci: PASS (122.37 s)
 (3/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_multi_fs_sources.with_cache.always.arm64-pci: STARTED
 (3/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_multi_fs_sources.with_cache.always.arm64-pci: PASS (218.56 s)
 (4/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_symbolic_link.with_cache.always.arm64-pci: STARTED
 (4/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_symbolic_link.with_cache.always.arm64-pci: PASS (122.30 s)
 (5/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_fio.with_cache.always.arm64-pci: STARTED
 (5/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_fio.with_cache.always.arm64-pci: PASS (221.92 s)
 (6/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.arm64-pci: STARTED
 (6/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_iozone.with_cache.always.arm64-pci: PASS (154.57 s)
 (7/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_pjdfstest.with_cache.always.arm64-pci: STARTED
 (7/7) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_pjdfstest.with_cache.always.arm64-pci: PASS (288.77 s)
```

2023-08-31 02:47 UTC, zhenyzha approved these changes

2023-08-31 02:48 UTC, PaulYuuu commented
Hello @fbq815, can you consider all platforms? https://github.com/avocado-framework/avocado-vt/pull/3666 has been merged, so it's time to refactor virtio-fs cfg files structure. To me, we can drop `mem_devs` and use `vm_mem_backend = memory-backend-file`, so we don't need `size_mem1 = ${mem}M`now, and use `vm_mem_backend` for all platforms can cut out many unnecessary lines, if the test case doesn't want to use numa/hugepage.

For example, the simplest code for `virtio_fs_readonly` is:
```INI
- virtio_fs_readonly:
    only Linux
    no RHEL.6 RHEL.7 RHEL.8.0 RHEL.8.1
    no Host_RHEL.m6 Host_RHEL.m7 Host_RHEL.m8.u0 Host_RHEL.m8.u1
    type = virtio_fs_readonly
    required_qemu = [4.2.0,)
    s390, s390x:
        required_qemu = [5.2.0,)
    kill_vm = yes
    start_vm = yes
    filesystems = fs
    fs_driver = virtio-fs
    fs_source_type = mount
    fs_source_dir = virtio_fs_test/
    force_create_fs_source = yes
    remove_fs_source = yes
    fs_target = 'myfs'
    fs_driver_props = {"queue-size": 1024}
    fs_dest = '/mnt/${fs_target}'
    vm_mem_backend = memory-backend-file
    vm_mem_backend_path = /dev/shm
    vm_mem_share = yes
    cmd_create_file = 'touch ${fs_dest}/fs_file'
    check_str = 'Read-only file system'
```

Besides, we still have some virtio-fs PRs pending, they should also update the cfg usage to deprecate the wrong dirty one. like https://github.com/autotest/tp-qemu/pull/3784

This can be the first entry(example) to handle part of cfgs, but the goal is to update all. cc @xiagao

2023-08-31 02:50 UTC, PaulYuuu requested changes
Please discuss the above issue, guys.

2023-09-05 07:25 UTC, fbq815 commented
Test result:
JOB ID     : a5beb099edab1c1df9f8cdec79db950446b66aa5
JOB LOG    : /root/avocado/job-results/job-2023-09-05T02.34-a5beb09/job.log
 (01/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.s390-virtio: STARTED
 (01/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.s390-virtio: PASS (24.50 s)
 (02/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_xattr.with_cache.none.s390-virtio: STARTED
 (02/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.with_xattr.with_cache.none.s390-virtio: PASS (30.78 s)
 (03/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.without_xattr.with_cache.none.s390-virtio: STARTED
 (03/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_sys_admin.without_xattr.with_cache.none.s390-virtio: PASS (30.10 s)
 (04/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.s390-virtio: STARTED
 (04/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.s390-virtio: PASS (29.19 s)
 (05/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.s390-virtio: STARTED
 (05/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_reboot.s390-virtio: PASS (40.88 s)
 (06/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_packed_on.s390-virtio: STARTED
 (06/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_packed_on.s390-virtio: PASS (29.29 s)
 (07/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.s390-virtio: STARTED
 (07/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.git_init.s390-virtio: PASS (28.92 s)
 (08/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.xattr_on.flock_off.lock_posix_off.s390-virtio: STARTED
 (08/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.xattr_on.flock_off.lock_posix_off.s390-virtio: PASS (28.47 s)
 (09/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.xattr_off.flock_off.lock_posix_off.s390-virtio: STARTED
 (09/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.xattr_off.flock_off.lock_posix_off.s390-virtio: PASS (28.19 s)
 (10/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_writeback.s390-virtio: STARTED
 (10/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.with_writeback.s390-virtio: PASS (28.88 s)
 (11/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: STARTED
 (11/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.s390-virtio: PASS (29.21 s)
 (12/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.xattr_on.flock_off.lock_posix_off.s390-virtio: STARTED
 (12/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.xattr_on.flock_off.lock_posix_off.s390-virtio: PASS (29.23 s)
 (13/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.xattr_off.flock_off.lock_posix_off.s390-virtio: STARTED
 (13/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.xattr_off.flock_off.lock_posix_off.s390-virtio: PASS (28.40 s)
 (14/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.with_writeback.s390-virtio: STARTED
 (14/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.always.with_writeback.s390-virtio: PASS (28.87 s)
 (15/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.s390-virtio: STARTED
 (15/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.s390-virtio: PASS (29.50 s)
 (16/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.xattr_on.flock_off.lock_posix_off.s390-virtio: STARTED
 (16/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.xattr_on.flock_off.lock_posix_off.s390-virtio: PASS (29.46 s)
 (17/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.xattr_off.flock_off.lock_posix_off.s390-virtio: STARTED
 (17/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.xattr_off.flock_off.lock_posix_off.s390-virtio: PASS (28.69 s)
 (18/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.s390-virtio: STARTED
 (18/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.with_cache.none.with_writeback.s390-virtio: PASS (29.07 s)
 (19/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_fio.with_cache.auto.s390-virtio: STARTED
 (19/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_fio.with_cache.auto.s390-virtio: PASS (149.45 s)
 (20/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.3.0.s390x.io-github-autotest-qemu.virtio_fs_share_data.run_stress.with_fio.with_cache.auto.with_writeback.s390-virtio: STARTED
 (20/27) Host_RHEL.m9.u3.nographic.qcow2.virtio_scsi.up.virtio_net.Gue [...]

2023-09-19 06:36 UTC, fbq815 commented
> Please discuss the above issue, guys.

as we discussed online in the meeting, I've updated this patch

2023-09-20 02:49 UTC, xiagao commented
(1/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: STARTED
 (1/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_readonly.q35: PASS (74.53 s)
 (2/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: STARTED
 (2/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.q35: PASS (92.04 s)
 (3/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: STARTED
 (3/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.q35: PASS (711.96 s)
 (4/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: STARTED
 (4/4) Host_RHEL.m9.u4.ovmf.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.x86_64.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.q35: PASS (109.66 s)
ACK

2023-09-20 02:50 UTC, xiagao approved these changes

2023-09-20 04:13 UTC, SiboWang1997 commented
(1/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: STARTED
 (1/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_readonly.arm64-pci: PASS (44.34 s)
 (2/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.arm64-pci: STARTED
 (2/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_multi_vms.share_fs_source.arm64-pci: PASS (131.94 s)
 (3/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.arm64-pci: STARTED
 (3/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_set_capability.remove_capability.cap_dac_read_search.with_cache.auto.arm64-pci: PASS (63.23 s)
 (4/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.arm64-pci: STARTED
 (4/4) Host_RHEL.m9.u4.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.9.4.0.aarch64.page_64k.io-github-autotest-qemu.virtio_fs_share_data.with_cache.auto.arm64-pci: PASS (66.62 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-09-19T23.59-f744e36/results.html
JOB TIME   : 308.59 s

LGTM,
Acked-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

2023-09-20 04:15 UTC, SiboWang1997 approved these changes

2023-09-21 02:28 UTC, MiriamDeng commented
Will provide test result within today, thanks.

2023-09-21 08:11 UTC, fbq815 commented
@PaulYuuu please help me review and merge this patch

2023-09-22 09:10 UTC, merged