Replace WMIC with powershell cmdlet
autotest/tp-qemu pull request #4242
Opened 2024-12-24 03:19 UTC by leidwang

From Win11-24H2, Windows remove WMIC, so replace it with some powershell cmdlet

2025-01-08 02:18 UTC, leidwang commented
depends on https://github.com/avocado-framework/avocado-vt/pull/4034

2025-01-08 02:20 UTC, leidwang commented
Hi @xiagao @heywji Would you please help test this MR with our acceptance test, thanks.

2025-01-08 02:47 UTC, heywji commented
OK. I am running the acceptance test within this patch and the avocado-vt patch. I will sync the test result when it is done.

2025-01-09 03:16 UTC, heywji approved these changes
Passed on the prewhql270 acceptance test.

2025-01-09 05:33 UTC, leidwang commented
> Passed on the prewhql270 acceptance test.

Great, thank you.

2025-01-15 06:26 UTC, xiagao commented
Test  271 acceptance with win2019,win2015 and win10-64 guests, this patch worked.

2025-01-15 06:41 UTC, heywji commented
Test 271 acceptance with win2022,win11,win1032 and win2016 guests, this patch worked.

2025-01-15 06:43 UTC, leidwang commented
Hi @XueqiangWei @nanliu-r @fbq815 Would you please help test this MR, it is mainly for wmic repalcement.Thanks.

2025-01-15 07:21 UTC, xiagao commented on qemu/tests/qemu_guest_agent.py
> -            vol_virtio_key = "VolumeName like '%virtio-win%'"
@leidwang is this a must for wmic replacement? It'll lead to failure.
After applying the two patches, lead to one failure.

C:\>wmic logicaldisk where (VolumeName='%virtio-win*')
No Instance(s) Available.

C:\>wmic logicaldisk where (VolumeName like '%virtio-win%') get DeviceID
DeviceID  
E: 

I don't know why still consuming the 'wmic' cmd in my tests.

2025-01-15 09:30 UTC, heywji requested changes

2025-01-15 09:30 UTC, heywji commented on qemu/tests/qemu_guest_agent.py
> +            vol_virtio_key = "VolumeName='%virtio-win*'"
Please help to remove the extra “%” here. This will cause problems in the acceptance test.

2025-01-15 10:29 UTC, leidwang commented on qemu/tests/qemu_guest_agent.py
> +            vol_virtio_key = "VolumeName='%virtio-win*'"
Done.

2025-01-15 13:29 UTC, heywji approved these changes
LGTM

```
 (1/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (1/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35:  PASS (825.80 s)
 (2/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (2/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35:  PASS (633.83 s)
 (3/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35: STARTED
 (3/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.unattended_install.cdrom.extra_cdrom_ks.default_install.aio_threads.q35:  PASS (1099.58 s)
 (4/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35: STARTED
 (4/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35:  PASS (147.48 s)
 (5/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35: STARTED
 (5/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win10.i386.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35:  PASS (116.34 s)
 (6/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35: STARTED
 (6/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35:  PASS (56.63 s)
 (7/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35: STARTED
 (7/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2016.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35:  PASS (48.22 s)
 (8/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35: STARTED
 (8/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_sync.q35:  PASS (102.38 s)
 (9/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35: STARTED
 (9/9) Host_RHEL.m10.u0.qcow2.virtio_scsi.up.virtio_net.Guest.Win2019.x86_64.io-github-autotest-qemu.qemu_guest_agent.virtio_serial.check_powerdown.q35:  PASS (83.43 s)
RESULTS    : PASS 9 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```

2025-01-16 01:46 UTC, xiagao commented
Acceptance test looks good.
LGTM.

2025-01-22 06:01 UTC, leidwang commented
Hi @yanan-fu @YongxueHong Would you please help review this MR?Thanks.

2025-01-24 12:11 UTC, mcasquer commented
@leidwang the L226 is still preserving the `wmic` command:
https://github.com/autotest/tp-qemu/blob/879c7d72a27da0941d09bee8d27f0c79b605378a/provider/block_devices_plug.py#L225

2025-02-05 03:48 UTC, YongxueHong commented
Hi @leidwang 
We recommand keeping the length of the line code within 79 characters for readability.
Thanks.

2026-05-25 14:26 UTC, harvey0100 commented
Closing this PR due to current team constraints. This is part of a broader effort to triage all in-flight work across our upstream repos. If this work is still needed, please feel free to reopen and it will be picked up. Apologies for any inconvenience.

2026-06-04 11:38 UTC, closed without merging